#!/bin/bash
#
# this script generate Dockerfile for staroid
#

bin="$(dirname "${BASH_SOURCE-$0}")"
bin="$(cd "${bin}">/dev/null; pwd)"

DOCKERFILE_BASE=${bin}/../Dockerfile
DOCKERFILE_STAROID=${bin}/Dockerfile_staroid
DOCKERFILE_GENERATED=${bin}/Dockerfile_generated

cat $DOCKERFILE_BASE > $DOCKERFILE_GENERATED
echo "" >> $DOCKERFILE_GENERATED
echo "# Generated by .staroid/gen_dockerfile.sh" >> $DOCKERFILE_GENERATED
cat $DOCKERFILE_STAROID >> $DOCKERFILE_GENERATED
