apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: superset
      context: .
      docker:
        dockerfile: .staroid/Dockerfile_generated
        buildArgs:
          NPM_BUILD_CMD: build
  local:
    concurrency: 2
deploy:
  statusCheckDeadlineSeconds: 600
  kubectl:
    manifests:
      - .staroid/k8s/env.yaml
      - .staroid/k8s/redis.yaml
      - .staroid/k8s/postgres.yaml
      - .staroid/k8s/superset.yaml
profiles:
  - name: minikube
    patches:
      - op: add
        path: /deploy/kubectl/manifests/0
        value: .staroid/k8s/minikube.yaml
